to quick demo of screenshot attachments made changes to make screenshots each time after test (not only for failed)
aquality-automation/aquality-appium-mobile-dotnet-template pull request #10
Opened 2020-09-10 13:48 UTC by mialeska

to quick demo of screenshot attachments made changes to make screenshots each time after test (not only for failed)

in the aquality settings changed:
- placeholders' text of dynamic variables
- projectId configured to 1 as default as 0 is not allowed

Also updated nuget package versions to latest compatible

2020-09-11 08:35 UTC, DmitryBogatko requested changes

2020-09-11 08:44 UTC, mialeska commented on Aquality.Appium.Mobile.Template/Aquality.Appium.Mobile.Template.SpecFlow/Hooks/ScreenshotHooks.cs
>                  TestContext.AddTestAttachment(pathToScreenshot);
already there https://github.com/aquality-automation/aquality-appium-mobile-dotnet-template/blob/Enhancement/make-screen-eachtime-after/Aquality.Appium.Mobile.Template/Aquality.Appium.Mobile.Template/Utilities/ScreenshotProvider.cs

2020-09-11 08:44 UTC, mialeska commented on Aquality.Appium.Mobile.Template/Aquality.Appium.Mobile.Template.SpecFlow/Hooks/ScreenshotHooks.cs
>                  var pathToScreenshot = screenshotProvider.TakeScreenshot();
it's png, take a look at ScreenshotProvider implementation https://github.com/aquality-automation/aquality-appium-mobile-dotnet-template/blob/Enhancement/make-screen-eachtime-after/Aquality.Appium.Mobile.Template/Aquality.Appium.Mobile.Template/Utilities/ScreenshotProvider.cs

2020-09-14 16:25 UTC, DmitryBogatko approved these changes

2020-09-14 16:25 UTC, merged